server:
  port: 8083

spring:
  application:
    name: service-passenger-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-passenger-user?charactorEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

